In [1]:
import numpy as np
import torch

In [2]:
arr1 = np.arange(30).reshape(10, 3)
arr1

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [24, 25, 26],
       [27, 28, 29]])

In [6]:
(
    (arr1.min(axis=0) + arr1.max(axis=0)) / 2
).shape

(3,)

In [7]:
px, py = np.meshgrid(np.arange(10), np.arange(20))
np.column_stack([px.flatten(), py.flatten()])

array([[ 0,  0],
       [ 1,  0],
       [ 2,  0],
       [ 3,  0],
       [ 4,  0],
       [ 5,  0],
       [ 6,  0],
       [ 7,  0],
       [ 8,  0],
       [ 9,  0],
       [ 0,  1],
       [ 1,  1],
       [ 2,  1],
       [ 3,  1],
       [ 4,  1],
       [ 5,  1],
       [ 6,  1],
       [ 7,  1],
       [ 8,  1],
       [ 9,  1],
       [ 0,  2],
       [ 1,  2],
       [ 2,  2],
       [ 3,  2],
       [ 4,  2],
       [ 5,  2],
       [ 6,  2],
       [ 7,  2],
       [ 8,  2],
       [ 9,  2],
       [ 0,  3],
       [ 1,  3],
       [ 2,  3],
       [ 3,  3],
       [ 4,  3],
       [ 5,  3],
       [ 6,  3],
       [ 7,  3],
       [ 8,  3],
       [ 9,  3],
       [ 0,  4],
       [ 1,  4],
       [ 2,  4],
       [ 3,  4],
       [ 4,  4],
       [ 5,  4],
       [ 6,  4],
       [ 7,  4],
       [ 8,  4],
       [ 9,  4],
       [ 0,  5],
       [ 1,  5],
       [ 2,  5],
       [ 3,  5],
       [ 4,  5],
       [ 5,  5],
       [ 6,  5],
       [ 7,  5],
       [ 8,  5

In [2]:
import numpy as np

In [4]:
np.arcsin(np.pi)

/tmp/ipykernel_127524/4098632852.py:1: RuntimeWarning: invalid value encountered in arcsin
  np.arcsin(np.pi)


nan

In [8]:
px, py = np.meshgrid(np.arange(3), np.arange(6))

x, y = np.moveaxis(
    np.column_stack([px.flatten(), py.flatten()]),
    -1, 0
)
print(x)
print(y)

[0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2]
[0 0 0 1 1 1 2 2 2 3 3 3 4 4 4 5 5 5]


In [18]:
from typing import NamedTuple

class GhostCL(NamedTuple) :
    p1: float
    
    
    
cl = GhostCL(p1=1)
cl._fields

('p1',)