In [1]:
cd ..

/media/hjp/FAAC278CAC27430D/HJP/KUAICV/Hand/AbsoluteTrack


In [2]:
pwd

'/media/hjp/FAAC278CAC27430D/HJP/KUAICV/Hand/AbsoluteTrack'

In [21]:
import os
import numpy as np
import lib.common.camera

IMG_WIDTH = 640
IMG_HEIGHT = 480



In [39]:
'''
%YAML:1.0
---
K1: !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [ 2.3877057700850656e+02, 0., 3.1846939219741773e+02, 0.,
       2.3903223316525276e+02, 2.4685137381795201e+02, 0., 0., 1. ]
K2: !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [ 2.3952183485043457e+02, 0., 3.1286224145189811e+02, 0.,
       2.3981379751051574e+02, 2.5158397962108106e+02, 0., 0., 1. ]
D1: !!opencv-matrix
   rows: 4
   cols: 1
   dt: d
   data: [ -3.7539305827469560e-02, -8.7553205432575471e-03,
       2.2015408171895236e-03, -6.6218076061138698e-04 ]
D2: !!opencv-matrix
   rows: 4
   cols: 1
   dt: d
   data: [ -3.6790400486095221e-02, -8.2041573433038941e-03,
       1.0552974220937024e-03, -2.5841665172692902e-04 ]
R: !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [ 9.9999267757707777e-01, -5.9888746804658943e-04,
       3.7796991979738852e-03, 6.1003792209015034e-04,
       9.9999546376609738e-01, -2.9496272580301179e-03,
       -3.7779155575739932e-03, 2.9519114194567365e-03,
       9.9998850672045803e-01 ]
T: !!opencv-matrix
   rows: 3
   cols: 1
   dt: d
   data: [ -5.9457914254177978e-02, -6.8318101539255457e-05,
       -1.8101725187729225e-04 ]
R1: !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [ 9.9997658245714527e-01, 5.5910744958795095e-04,
       6.8206990981942916e-03, -5.4903304536865717e-04,
       9.9999875583076248e-01, -1.4788169738349651e-03,
       -6.8215174296769373e-03, 1.4750375543776898e-03,
       9.9997564528550886e-01 ]
R2: !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [ 9.9999470555416226e-01, 1.1490100298631428e-03,
       3.0444440536135159e-03, -1.1535052313709361e-03,
       9.9999824663038117e-01, 1.4751819698614872e-03,
       -3.0427437166985561e-03, -1.4786859417328980e-03,
       9.9999427758290704e-01 ]
P1: !!opencv-matrix
   rows: 3
   cols: 4
   dt: d
   data: [ 1.2147550483213526e+02, 0., -1.3989139584901773e+02, 0., 0.,
       1.2147550483213526e+02, 2.7504092829903675e+02, 0., 0., 0., 1.,
       0. ]
P2: !!opencv-matrix
   rows: 3
   cols: 4
   dt: d
   data: [ 1.2147550483213526e+02, 0., -1.3989139584901773e+02,
       -7.2227183905833998e+00, 0., 1.2147550483213526e+02,
       2.7504092829903675e+02, 0., 0., 0., 1., 0. ]
Q: !!opencv-matrix
   rows: 4
   cols: 4
   dt: d
   data: [ 1., 0., 0., 1.3989139584901773e+02, 0., 1., 0.,
       -2.7504092829903675e+02, 0., 0., 0., 1.2147550483213526e+02, 0.,
       0., 1.6818529847502933e+01, 0. ]

'''
IMG_WIDTH = 640
IMG_HEIGHT = 480

left_to_right_r = np.array([
    9.9997658245714527e-01, 5.5910744958795095e-04, 6.8206990981942916e-03,
    -5.4903304536865717e-04, 9.9999875583076248e-01, -1.4788169738349651e-03,
    -6.8215174296769373e-03, 1.4750375543776898e-03, 9.9997564528550886e-01
]).reshape(3, 3)

left_to_right_t = np.array([
    -5.9457914254177978e-02, -6.8318101539255457e-05, -1.8101725187729225e-04
])




# k1, k2, k3, k4, p1, p2, k5, k6
distortion_coeffs_left = (
    -3.7539305827469560e-02, 
    -8.7553205432575471e-03,
    2.2015408171895236e-03, 
    -6.6218076061138698e-04,
    0, 0, 0, 0
)
camera_to_world_xf_left = np.eye(4)
rotation_left = np.array([
    [9.9997658245714527e-01,  5.5910744958795095e-04,  6.8206990981942916e-03,],
    [-5.4903304536865717e-04, 9.9999875583076248e-01, -1.4788169738349651e-03,],
    [-6.8215174296769373e-03, 1.4750375543776898e-03,  9.9997564528550886e-01 ],
]).reshape(3, 3)
camera_to_world_xf_left[:3, :3] = rotation_left
#camera_to_world_xf_left[:3, 3] = [
cam_left = lib.common.camera.Fisheye62CameraModel(
    width   = IMG_WIDTH,
    height  = IMG_HEIGHT,
    f       = (2.3877057700850656e+02, 2.3903223316525276e+02),
    c       = (3.1846939219741773e+02, 2.4685137381795201e+02),
    distort_coeffs = distortion_coeffs_left,
    camera_to_world_xf = np.eye(4)
)


distortion_coeffs_right = (
    -3.6790400486095221e-02, 
    -8.2041573433038941e-03,
    1.0552974220937024e-03, 
    -2.5841665172692902e-04,
    0, 0, 0, 0
)
camera_to_world_xf_right = np.eye(4)
rotation_right = np.array([
    [9.9999470555416226e-01, 1.1490100298631428e-03, 3.0444440536135159e-03,],
    [-1.1535052313709361e-03, 9.9999824663038117e-01, 1.4751819698614872e-03,],
    [-3.0427437166985561e-03, -1.4786859417328980e-03, 9.9999427758290704e-01 ],
]).reshape(3, 3)
camera_to_world_xf_right[:3, :3] = rotation_right
camera_to_world_xf_right[:3, 3] = left_to_right_t
#camera_to_world_xf_right[:3, 3] = [
cam_right = lib.common.camera.Fisheye62CameraModel(
    width   = IMG_WIDTH,
    height  = IMG_HEIGHT,
    f       = (2.3952183485043457e+02, 2.3981379751051574e+02),
    c       = (3.1286224145189811e+02, 2.5158397962108106e+02),
    distort_coeffs = distortion_coeffs_right,
    camera_to_world_xf = camera_to_world_xf_right
)

In [41]:
import plotly.graph_objects as go
import numpy as np

# Use the already defined IMG_WIDTH, IMG_HEIGHT, and camera models (cam_left, cam_right)

def create_camera_visualization(camera_model, color):
    # Extract camera parameters
    f = camera_model.f
    c = camera_model.c
    camera_to_world_xf = camera_model.camera_to_world_xf

    # Create camera frustum
    focal_length = (f[0] + f[1]) / 2
    frustum_length = 0.1  # Adjust this value to change the size of the frustum
    frustum_points = np.array([
        [0, 0, 0],
        [-IMG_WIDTH/2/focal_length, -IMG_HEIGHT/2/focal_length, 1],
        [IMG_WIDTH/2/focal_length, -IMG_HEIGHT/2/focal_length, 1],
        [IMG_WIDTH/2/focal_length, IMG_HEIGHT/2/focal_length, 1],
        [-IMG_WIDTH/2/focal_length, IMG_HEIGHT/2/focal_length, 1]
    ]) * frustum_length

    # Transform frustum points to world coordinates
    frustum_points = np.hstack((frustum_points, np.ones((5, 1))))
    frustum_points = (camera_to_world_xf @ frustum_points.T).T[:, :3]

    # Create lines for camera frustum
    lines = []
    for i in range(1, 5):
        lines.append(go.Scatter3d(x=[frustum_points[0, 0], frustum_points[i, 0]],
                                  y=[frustum_points[0, 1], frustum_points[i, 1]],
                                  z=[frustum_points[0, 2], frustum_points[i, 2]],
                                  mode='lines',
                                  line=dict(color=color, width=2)))

    for i in range(4):
        j = (i + 1) % 4 + 1
        lines.append(go.Scatter3d(x=[frustum_points[i, 0], frustum_points[j, 0]],
                                  y=[frustum_points[i, 1], frustum_points[j, 1]],
                                  z=[frustum_points[i, 2], frustum_points[j, 2]],
                                  mode='lines',
                                  line=dict(color=color, width=2)))

    # Create camera center point
    camera_center = go.Scatter3d(x=[camera_to_world_xf[0, 3]],
                                 y=[camera_to_world_xf[1, 3]],
                                 z=[camera_to_world_xf[2, 3]],
                                 mode='markers',
                                 marker=dict(size=5, color=color))

    return lines + [camera_center]

# Create visualization
fig = go.Figure()

# Add left camera visualization
left_camera_vis = create_camera_visualization(cam_left, 'blue')
fig.add_traces(left_camera_vis)

# Add right camera visualization
right_camera_vis = create_camera_visualization(cam_right, 'red')
fig.add_traces(right_camera_vis)

# Set layout
fig.update_layout(
    scene=dict(
        xaxis_title='X',
        yaxis_title='Y',
        zaxis_title='Z',
        aspectmode='data'
    ),
    title='Stereo Camera Visualization',
    showlegend=False
)

# Add text annotations for left and right cameras
# fig.add_annotation(
#     x=cam_left.camera_to_world_xf[0, 3],
#     y=cam_left.camera_to_world_xf[1, 3],
#     z=cam_left.camera_to_world_xf[2, 3],
#     text="Left Camera",
#     showarrow=True,
#     arrowhead=2,
#     arrowsize=1,
#     arrowwidth=2,
#     arrowcolor='blue'
# )

# fig.add_annotation(
#     x=cam_right.camera_to_world_xf[0, 3],
#     y=cam_right.camera_to_world_xf[1, 3],
#     z=cam_right.camera_to_world_xf[2, 3],
#     text="Right Camera",
#     showarrow=True,
#     arrowhead=2,
#     arrowsize=1,
#     arrowwidth=2,
#     arrowcolor='red'
# )

# Show plot
fig.show()


In [27]:
left_to_right_r = np.array([
    9.9997658245714527e-01, 5.5910744958795095e-04, 6.8206990981942916e-03,
    -5.4903304536865717e-04, 9.9999875583076248e-01, -1.4788169738349651e-03,
    -6.8215174296769373e-03, 1.4750375543776898e-03, 9.9997564528550886e-01
]).reshape(3, 3)
left_to_right_t = np.array([
    -5.9457914254177978e-02, -6.8318101539255457e-05, -1.8101725187729225e-04
])

left_to_right_xf = np.eye(4)
left_to_right_xf[:3, :3] = left_to_right_r
left_to_right_xf[:3, 3] = left_to_right_t

In [32]:
print(left_to_right_xf @ camera_to_world_xf_left)
print(camera_to_world_xf_right)
print(camera_to_world_xf_right @ left_to_right_xf)

[[ 9.99906331e-01  1.12826190e-03  1.36402455e-02 -5.94579143e-02]
 [-1.08796477e-03  9.99995023e-01 -2.96134088e-03 -6.83181015e-05]
 [-1.36435188e-02  2.94622339e-03  9.99902582e-01 -1.81017252e-04]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
[[ 0.99999471  0.00114901  0.00304444  0.        ]
 [-0.00115351  0.99999825  0.00147518  0.        ]
 [-0.00304274 -0.00147869  0.99999428  0.        ]
 [ 0.          0.          0.          1.        ]]
[[ 9.99949890e-01  1.71260376e-03  9.86333372e-03 -5.94582291e-02]
 [-1.71257328e-03  9.99998533e-01 -1.15360508e-05  2.37969142e-17]
 [-9.86333901e-03 -5.35620908e-06  9.99951356e-01  1.37531046e-16]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]


In [38]:
print(rotation_left)
print()
print(left_to_right_r @ rotation_left)
print()
print(rotation_right)
print()
print(rotation_left @ left_to_right_r)

[[ 9.99976582e-01  5.59107450e-04  6.82069910e-03]
 [-5.49033045e-04  9.99998756e-01 -1.47881697e-03]
 [-6.82151743e-03  1.47503755e-03  9.99975645e-01]]

[[ 0.99990633  0.00112826  0.01364025]
 [-0.00108796  0.99999502 -0.00296134]
 [-0.01364352  0.00294622  0.99990258]]

[[ 0.99999471  0.00114901  0.00304444]
 [-0.00115351  0.99999825  0.00147518]
 [-0.00304274 -0.00147869  0.99999428]]

[[ 0.99990633  0.00112826  0.01364025]
 [-0.00108796  0.99999502 -0.00296134]
 [-0.01364352  0.00294622  0.99990258]]


In [19]:

from lib.models.model_loader import load_pretrained_model
from lib.tracker.tracker import HandTracker, HandTrackerOpts, InputFrame, ViewData


In [22]:
model_name = "pretrained_weights.torch"
model_path = os.path.join(".", "pretrained_models", model_name)
model = load_pretrained_model(model_path)
model.eval()
tracker = HandTracker(model, HandTrackerOpts())

In [ ]:
tracker.